name: drupal
recipe: drupal8
config:
  xdebug: true

services:
  appserver:
    run:
      - "echo Downloading Drupal...&& drush pm-download --yes --drupal-project-rename=. --destination=$LANDO_MOUNT"
