name: drupal
recipe: drupal8
config:
  xdebug: true

services:
  appserver:
    build:
      - echo "Downloading Drupal..."
      - mv .lando.yml ~/.lando.yml && drush pm-download drupal --yes --dev --drupal-project-rename=. --destination=$LANDO_MOUNT"; mv ~/.lando.yml .lando.yml
